/**
 * Contract configuration for wagmi hooks.
 *
 * Addresses are loaded from src/addresses.json (generated by scripts/export-addresses.mjs
 * after forge deploy). ABIs come from typechain.
 */

import { parseAbi, type Address } from 'viem'
import {
  type ContractAddresses,
  VaultABI,
  RouterABI,
  PositionManagerABI,
  PriceFeedABI,
  ERC20ABI,
} from '../../packages/contracts/typechain'
import deployedAddresses from '../addresses.json'

// Market definitions
export interface MarketConfig {
  symbol: string
  baseAsset: string
  indexToken: Address
}

// Load addresses from the deploy export (runtime, not hardcoded)
const localAddresses: ContractAddresses = {
  usdc: deployedAddresses.usdc as Address,
  weth: deployedAddresses.weth as Address,
  wbtc: deployedAddresses.wbtc as Address,
  ethOracle: (deployedAddresses.ethOracle ?? '0x') as Address,
  btcOracle: (deployedAddresses.btcOracle ?? '0x') as Address,
  plp: (deployedAddresses.plp ?? '0x') as Address,
  priceFeed: deployedAddresses.priceFeed as Address,
  vault: deployedAddresses.vault as Address,
  positionManager: deployedAddresses.positionManager as Address,
  router: deployedAddresses.router as Address,
}

export function getAddresses(chainId: number): ContractAddresses {
  if (chainId === 31337) return localAddresses
  throw new Error(`No addresses for chainId ${chainId}`)
}

export function getMarkets(addresses: ContractAddresses): MarketConfig[] {
  return [
    { symbol: 'ETH-PERP', baseAsset: 'ETH', indexToken: addresses.weth },
    { symbol: 'BTC-PERP', baseAsset: 'BTC', indexToken: addresses.wbtc },
  ]
}

// Parse ABIs
const vaultAbi = parseAbi(VaultABI)
const routerAbi = parseAbi(RouterABI)
const positionManagerAbi = parseAbi(PositionManagerABI)
const priceFeedAbi = parseAbi(PriceFeedABI)
const erc20Abi = parseAbi(ERC20ABI)
const mockErc20Abi = parseAbi([
  ...ERC20ABI,
  'function mint(address to, uint256 amount) external',
])

export function getContracts(chainId: number) {
  const addresses = getAddresses(chainId)

  return {
    vault: { address: addresses.vault, abi: vaultAbi } as const,
    router: { address: addresses.router, abi: routerAbi } as const,
    positionManager: { address: addresses.positionManager, abi: positionManagerAbi } as const,
    priceFeed: { address: addresses.priceFeed, abi: priceFeedAbi } as const,
    usdc: { address: addresses.usdc, abi: erc20Abi } as const,
    usdcMock: { address: addresses.usdc, abi: mockErc20Abi } as const,
    plp: { address: addresses.plp, abi: erc20Abi } as const,
    addresses,
  }
}

export type { ContractAddresses }
