#!/usr/bin/env node

/**
 * Export ABIs from Foundry artifacts to a clean abi/ directory.
 * Also generates a deployments JSON from the latest broadcast.
 *
 * Usage: node scripts/export-abi.mjs
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const OUT_DIR = join(ROOT, "out");
const ABI_DIR = join(ROOT, "abi");
const DEPLOYMENTS_DIR = join(ROOT, "deployments");

// Contracts to export (name must match the .sol filename)
const CONTRACTS = [
  "Vault",
  "PositionManager",
  "Router",
  "PriceFeed",
  "PLP",
  "MockERC20",
  "MockChainlinkAggregator",
];

function exportAbis() {
  mkdirSync(ABI_DIR, { recursive: true });

  const exported = [];

  for (const name of CONTRACTS) {
    // Foundry outputs to out/<Name>.sol/<Name>.json
    const artifactPath = join(OUT_DIR, `${name}.sol`, `${name}.json`);

    if (!existsSync(artifactPath)) {
      console.warn(`  SKIP: ${name} (no artifact at ${artifactPath})`);
      continue;
    }

    const artifact = JSON.parse(readFileSync(artifactPath, "utf-8"));
    const abi = artifact.abi;

    if (!abi || abi.length === 0) {
      console.warn(`  SKIP: ${name} (empty ABI)`);
      continue;
    }

    // Write clean ABI JSON
    const outPath = join(ABI_DIR, `${name}.json`);
    writeFileSync(outPath, JSON.stringify(abi, null, 2) + "\n");
    exported.push(name);
    console.log(`  ✓ ${name} (${abi.length} entries)`);
  }

  // Write an index that re-exports all ABIs
  const indexLines = exported.map(
    (name) => `export { default as ${name}ABI } from "./${name}.json" with { type: "json" };`
  );
  // Also write a CommonJS-friendly version
  const cjsLines = exported.map(
    (name) => `  ${name}: require("./${name}.json"),`
  );

  writeFileSync(
    join(ABI_DIR, "index.ts"),
    [
      "// Auto-generated by scripts/export-abi.mjs — do not edit",
      ...exported.map(
        (name) => `import ${name}ABI from "./${name}.json";`
      ),
      "",
      "export {",
      ...exported.map((name) => `  ${name}ABI,`),
      "};",
      "",
    ].join("\n")
  );

  console.log(`\nExported ${exported.length} ABIs to abi/`);
  return exported;
}

function exportDeployments() {
  mkdirSync(DEPLOYMENTS_DIR, { recursive: true });

  // Look for the latest Anvil broadcast (chain 31337)
  const broadcastDir = join(ROOT, "broadcast", "DeployLocal.s.sol", "31337");

  if (!existsSync(broadcastDir)) {
    console.log("\nNo local deployment found (run deploy:local first)");
    return;
  }

  // Find the latest run file
  const files = readdirSync(broadcastDir).filter((f) => f.startsWith("run-latest"));
  if (files.length === 0) {
    console.log("\nNo broadcast run found");
    return;
  }

  const runFile = join(broadcastDir, files[0]);
  const run = JSON.parse(readFileSync(runFile, "utf-8"));

  // Extract contract addresses from CREATE transactions
  const addresses = {};
  for (const tx of run.transactions || []) {
    if (tx.transactionType === "CREATE" && tx.contractName) {
      addresses[tx.contractName] = tx.contractAddress;
    }
  }

  const deployment = {
    chainId: 31337,
    network: "anvil",
    timestamp: new Date().toISOString(),
    contracts: addresses,
  };

  writeFileSync(
    join(DEPLOYMENTS_DIR, "localhost.json"),
    JSON.stringify(deployment, null, 2) + "\n"
  );

  console.log(`\nDeployment addresses exported to deployments/localhost.json`);
  console.log(JSON.stringify(addresses, null, 2));
}

console.log("=== Exporting ABIs ===\n");
exportAbis();
exportDeployments();
