export { TrendLineTool } from './TrendLine.js';
export { HorizontalLineTool } from './HorizontalLine.js';
export { VerticalLineTool } from './VerticalLine.js';
export { RayTool } from './Ray.js';
export { ExtendedLineTool } from './ExtendedLine.js';
export { ParallelChannelTool } from './ParallelChannel.js';
export { RegressionChannelTool } from './RegressionChannel.js';
export { FibRetracementTool } from './FibRetracement.js';
export { FibExtensionTool } from './FibExtension.js';
export { RectangleTool } from './Rectangle.js';
export { EllipseTool } from './Ellipse.js';
export { TriangleTool } from './Triangle.js';
export { PitchforkTool } from './Pitchfork.js';
export { ElliottWaveTool } from './ElliottWave.js';
export { PriceRangeTool } from './PriceRange.js';
export { DateRangeTool } from './DateRange.js';
export { MeasureTool } from './Measure.js';
export { TextAnnotationTool } from './TextAnnotation.js';
export { ArrowTool } from './Arrow.js';
export { GannFanTool } from './GannFan.js';
export { GannBoxTool } from './GannBox.js';
export { AnchoredVWAPTool } from './AnchoredVWAP.js';
export { VolumeProfileRangeTool } from './VolumeProfileRange.js';

import type { DrawingManager } from '../DrawingManager.js';
import { TrendLineTool } from './TrendLine.js';
import { HorizontalLineTool } from './HorizontalLine.js';
import { VerticalLineTool } from './VerticalLine.js';
import { RayTool } from './Ray.js';
import { ExtendedLineTool } from './ExtendedLine.js';
import { ParallelChannelTool } from './ParallelChannel.js';
import { RegressionChannelTool } from './RegressionChannel.js';
import { FibRetracementTool } from './FibRetracement.js';
import { FibExtensionTool } from './FibExtension.js';
import { RectangleTool } from './Rectangle.js';
import { EllipseTool } from './Ellipse.js';
import { TriangleTool } from './Triangle.js';
import { PitchforkTool } from './Pitchfork.js';
import { ElliottWaveTool } from './ElliottWave.js';
import { PriceRangeTool } from './PriceRange.js';
import { DateRangeTool } from './DateRange.js';
import { MeasureTool } from './Measure.js';
import { TextAnnotationTool } from './TextAnnotation.js';
import { ArrowTool } from './Arrow.js';
import { GannFanTool } from './GannFan.js';
import { GannBoxTool } from './GannBox.js';
import { AnchoredVWAPTool } from './AnchoredVWAP.js';
import { VolumeProfileRangeTool } from './VolumeProfileRange.js';

export function registerBuiltInDrawingTools(manager: DrawingManager): void {
  manager.register(new TrendLineTool());
  manager.register(new HorizontalLineTool());
  manager.register(new VerticalLineTool());
  manager.register(new RayTool());
  manager.register(new ExtendedLineTool());
  manager.register(new ParallelChannelTool());
  manager.register(new RegressionChannelTool());
  manager.register(new FibRetracementTool());
  manager.register(new FibExtensionTool());
  manager.register(new RectangleTool());
  manager.register(new EllipseTool());
  manager.register(new TriangleTool());
  manager.register(new PitchforkTool());
  manager.register(new ElliottWaveTool());
  manager.register(new PriceRangeTool());
  manager.register(new DateRangeTool());
  manager.register(new MeasureTool());
  manager.register(new TextAnnotationTool());
  manager.register(new ArrowTool());
  manager.register(new GannFanTool());
  manager.register(new GannBoxTool());
  manager.register(new AnchoredVWAPTool());
  manager.register(new VolumeProfileRangeTool());
}
